### ISSUE TITLE
Screen rotation

### ISSUE THREAD

**Issue by ibakayoko** [ricardoalcocer/alloy-widget-drawermenu#1]
On android real phone or emulator.
If you change the screen orientation while the app is loading (on splash screen) you get the following error
Location:
[44,57] alloy/widgets/com.drawermenu.widget/controllers/widget.js
Message:
"Uncaught TypeError: Cannot read property 'paltformWidth' of undefined"
Source:
$.drawermainview.width=Ti.Platform.displayCaps.platformWidth;

---

Log from emulator
[INFO][ActivityManager( 277)] Config changes=1480 {1.0 310mcc260mnc en_US ldltr sw320dp w527dp h294dp 240dpi nrml land finger -keyb/v/h tball/v s.40} [INFO][InputReader( 277)] Reconfiguring input devices. changes=0x00000004 [INFO][InputReader( 277)] Device reconfigured: id=0, name='qwerty2', size 480x854, orientation 1, mode 1, display id 0
[ERROR][TiExceptionHandler( 1884)](main) [823,5245] ----- Titanium Javascript Runtime Error -----
[ERROR][TiExceptionHandler( 1884)](main) [3,5248] - In alloy/widgets/com.drawermenu.widget/controllers/widget.js:44,57
[ERROR][TiExceptionHandler( 1884)](main) [17,5265] - Message: Uncaught TypeError: Cannot read property 'platformWidth' of undefined
[ERROR][TiExceptionHandler( 1884)](main) [7,5272] - Source: $.drawermainview.width = Ti.Platform.displayCaps.platformWidth;
## [ERROR][V8Exception( 1884)] Exception occurred at alloy/widgets/com.drawermenu.widget/controllers/widget.js:44: Uncaught TypeError: Cannot read property 'platformWidth' of undefined

Same issue created on http://developer.appcelerator.com/question/157633/alloy---drawermenu---widget

**Comment by lockheedc130** [comment]
can't confirm. is working fine for me

**Comment by ibakayoko** [comment]
![device-2013-10-21-144930](https://f.cloud.github.com/assets/3247064/1375427/97b908ec-3a81-11e3-898c-1a5202cb65d8.png)

**Comment by ibakayoko** [comment]
lockheedc130 . To reproduce the error you got to rotate the screen while on splash screen.
If the app is already loaded you do not get the error.

[INFO][InputReader(  275)] Device reconfigured: id=0, name='qwerty2', size 480x854, orientation 1, mode 1, display id 0
[INFO][dalvikvm-heap( 1211)] Grow heap (frag case) to 5.975MB for 1536016-byte allocation
[INFO][dalvikvm-heap(  417)] Grow heap (frag case) to 10.041MB for 6410576-byte allocation
[INFO][dalvikvm-heap(  417)] Grow heap (frag case) to 12.919MB for 3019760-byte allocation
[INFO][ActivityManager(  275)] START u0 {cmp=ti.drawerdemo/org.appcelerator.titanium.TiActivity (has extras)} from pid 1211
[WARN][WindowManager(  275)] Failure taking screenshot for (236x421) to layer 21010
[ERROR][TiExceptionHandler( 1211)](main) [3876,3876] ----- Titanium Javascript Runtime Error -----
[ERROR][TiExceptionHandler( 1211)](main) [3,3879] - In alloy/widgets/com.drawermenu.widget/controllers/widget.js:44,57
[ERROR][TiExceptionHandler( 1211)](main) [13,3892] - Message: Uncaught TypeError: Cannot read property 'platformWidth' of undefined
[ERROR][TiExceptionHandler( 1211)](main) [3,3895] - Source:         $.drawermainview.width = Ti.Platform.displayCaps.platformWidth;
[ERROR][V8Exception( 1211)] Exception occurred at alloy/widgets/com.drawermenu.widget/controllers/widget.js:44: Uncaught TypeError: Cannot read property 'platformWidth' of undefined
[INFO][Choreographer( 1211)] Skipped 121 frames!  The application may be doing too much work on its main thread.
