### ISSUE TITLE
Demos failing when launching...

### ISSUE THREAD

**Issue by john-dalsgaard** [ricardoalcocer/alloy-widget-drawermenu#10]
Hi

This widget looks like what I need. I have found many with classic code - but I really want to use Alloy instead ;-)

I have downloaded the project and tried to run the demos on iPhone. However, they fail at the same place in index.js:

$.drawermenu.addEventListener('open', function menuOpen () {
    Ti.API.info("Menu opened");
});

The error is (here from tishadow - but it is the same if run directly):

[ERROR] [iphone, 7.1, 192.168.42.38] TypeError: 'undefined' is not a function (evaluating '$.drawermenu.addEventListener("open", function() {
        __log.info("Menu opened");
    })')

I have tried the "demo" app inside the project. I also tried to use the "ActionBar Demo" - for Android emulator (using titanium_17_WVGA854). It failed either with a timeout or with "Not enough free space on the device". Then I tried to enable iPhone in tiapp.xml - but that fails with the same error as above?

What am I missing to make this run? 

I'am on Mac OS 10.9.3 and Studio 3.2.3

/John

**Comment by batuhanc** [comment]
Hi,

I'm also interested in this widget but cannot run demos. I get the similar error on iOS simulator;

'undefined' is not a function (evaluating '$.drawermenu.addEventListener("open", function() {
__log.info("Menu opened");
})') at index.js (line 53)

![image](https://cloud.githubusercontent.com/assets/2908928/3486536/68baa56c-0440-11e4-8a6d-b0a572ee64c4.png)

My Titanium SDK is 3.2.3. Any solution to this?

Thanks.

**Comment by xavierledoux** [comment]
Hi,

I'm having the same problem too. The demo starts only when I comment those lines in index.js

$.drawermenu.addEventListener('open', function menuOpen () {
    Ti.API.info("Menu opened");
});

$.drawermenu.addEventListener('close', function menuOpen () {
    Ti.API.info("Menu closed");
});

Moreover, when I try too use the module in my own app, I can't load the mainView, only the menuView is loaded. Any solution for that problem ?

My Titanium SDK is 3.2.3.

Thank you.

**Comment by n2bSolutions** [comment]
I not sure but Did you tried '$.drawermenu.getView().addEventListener("open", .........
})'
Only change on index.js 
$.drawermenu.  
by 
$.drawermenu.getView().

**Comment by awamser** [comment]
I just tested n2bSolutions and it's correct, just add the getView().
