### ISSUE TITLE
add multiple views and switch between views

### ISSUE THREAD

**Issue by saldisobi** [ricardoalcocer/alloy-widget-drawermenu#11]
how to switch between views on item click from slide menu

**Comment by ricardoalcocer** [comment]
You could either load your views upon click onto the mainView, or you could use a ScrollableView (http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.ScrollableView), load your views into it, and upon click, simply change the page of the ScrollableView.

R
