### ISSUE TITLE
Recalculation of width

### ISSUE THREAD

**Issue by JuanuMusic** [ricardoalcocer/alloy-widget-drawermenu#7]
Hi Ricardo!
I've been having some issues with the width recalculation, and found out that this line is useless:
if (OS_ANDROID)
        newWidth /= Ti.Platform.displayCaps.logicalDensityFactor;

In android, by just using Ti.Platform.displayCaps.logicalDensityFactor works just fine;
In fact, it messes up with the width of the main container if you divide the new width with the logical density factor.

Cand you explain exactly why this is set?
In my case it was safe to remove it and I can pull a request to merge my changes, unless we can figure out why is that line important!

Saludos!

**Comment by ricardoalcocer** [comment]
Hola,
That was added by - someone - and I merged it because it didn't exhibit any misbehavior.  If you've tested it and works without that line, feel free to send a PR.  Please make sure you update the widget on the subfolders of the sample apps as well.

Thanks.

R
